import { Comida } from '../interfaces/comida';

export const COMIDAS: Comida[] = [
  {
    id: 2,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Jamón Ibérico De Bellota',
    plato_ingles: 'Iberian Ham',
    formato_tapa: 0,
    formato_media: 11.95,
    formato_racion: 23.95,
    alergenos: '',
    top: true,
    new: false,
  },
  {
    id: 18,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Jamón Ibérico De Bellota Y Queso Curado De Oveja',
    plato_ingles: 'Iberian Ham And Sheep´s Cheese',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.95,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 3,
    seccion: ['Verde Que Te Quiero Verde'],
    plato:
      'Ensalada Mixta Con Lechuga, Cebolla, Atún, Tomate Y Zanahoria Rallada -- Ya Está Aliñada',
    plato_ingles: 'Mixta: Lettuce, Tomato, Onion, Cucumber, Carrot And Tuna',
    formato_tapa: 0,
    formato_media: 6.45,
    formato_racion: 8.45,
    alergenos: 'PESCADO',
    top: false,
    new: true,
  },

  {
    id: 4,
    seccion: ['Para Compartir'],
    plato:
      'Ensaladilla De Patatas, Zanahoria, Dados De Atún JC Mackintosh, Mayonesa Con Ajo Confitado Y Huevo Frito En Virgen Extra',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.95,
    alergenos: 'PESCADO - HUEVOS - LACTEOS - CRUSTÁCEOS',
    top: true,
    new: false,
  },
  {
    id: 5,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Pan Bao Blanco - Con Jarrete, Verduras Y Salsa Yakitori',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.55,
    alergenos: 'GLUTEN - LACTEO - HUEVO',
    top: false,
    new: false,
  },

  {
    id: 81,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Carne Madurada De Vaca, Noodles, Queso Rallado, Salsa Japonesa Y Barbacoa',
    plato_ingles:
      'Mini Beef Matured Beef Burger, Noodles, Grated Cheese, Japanese Sauce and Barbecue',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.45,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: true,
    new: false,
  },

  {
    id: 16,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Jamón Ibérico De Bellota Y Pata Al Horno Con AOVE y Sal',
    plato_ingles: 'Iberian Ham and Roast Pork And Extra Virgin Olive Oil',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.95,
    alergenos: 'LÁCTEOS',
    top: false,
    new: false,
  },

  {
    id: 18,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Pata De Cerdo Al Horno Con AOVE y Sal',
    plato_ingles: 'Roast Pork And Extra Virgin Olive Oil',
    formato_tapa: 2.5,
    formato_media: 7.45,
    formato_racion: 9.75,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 18,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Queso Curado De Oveja',
    plato_ingles: 'Sheep Cheese',
    formato_tapa: 2.5,
    formato_media: 7.45,
    formato_racion: 12.5,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 17,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato:
      'Huevos Con Jamón Ibérico De Bellota -  Con Patatas, 3 Huevos De Campo y Jamón De Ibérico De Bellota Cortado A Cuchillo',
    plato_ingles: 'Chips, Three Fried Eggs And Iberian Ham',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 15.95,
    alergenos: 'GLUTEN',
    top: false,
    new: true,
  },

  {
    id: 19,
    seccion: ['Verde Que Te Quiero Verde'],
    plato: 'Pimientos De Padrón Fritos En Virgen Extra',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.95,
    alergenos: 'GLUTEN',
    top: false,
    new: false,
  },
  {
    id: 19,
    seccion: ['Verde Que Te Quiero Verde'],
    plato:
      'Chips De Berenjena - Finas Láminas De Berenjena, Fritas En Aceite De Oliva Virgen Extra',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.9,
    alergenos: 'GLUTEN - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 20,
    seccion: ['Verde Que Te Quiero Verde'],
    plato:
      'Ensalada Con Tomate Pelado, Tiras De Aguacate, Cebolla Morada Y Vinagreta',
    plato_ingles:
      'Salad With Peeled Tomato, Avocado Strips, Red Onion And Vinaigrette',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 21,
    seccion: ['Verde Que Te Quiero Verde'],
    plato: 'Espárragos Verdes Al Ajillo',
    plato_ingles:
      'Grilled Green Asparagus With Garlic And Extra Virgin Olive Oil',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 7.25,
    alergenos: '',
    top: true,
    new: false,
  },

  {
    id: 23,
    seccion: ['Para Compartir'],
    plato: 'Gambones A La Plancha',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.9,
    alergenos: 'PESCADO',
    top: false,
    new: false,
  },
  {
    id: 24,
    seccion: ['Para Compartir'],
    plato: 'Tartar De Atún Rojo, Cebolla, Base Aguacate Y Soja',
    plato_ingles: 'Tuna Tartar',
    formato_tapa: 8.5,
    formato_media: 0,
    formato_racion: 16.5,
    alergenos: 'GLUTEN - PESCADO - SOJA',
    top: true,
    new: false,
  },
  {
    id: 25,
    seccion: ['Para Compartir'],
    plato: 'Paté de perdiz',
    plato_ingles: 'Partridge Pate And Caramelized Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 8.55,
    alergenos: 'GLUTEN - LÁCTEO',
    top: false,
    new: false,
  },
  {
    id: 26,
    seccion: ['Para Compartir'],
    plato: 'Paté De Boletus Y Queso',
    plato_ingles: 'Partridge Pate And Caramelized Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 8.95,
    alergenos: 'GLUTEN - LÁCTEO',
    top: false,
    new: false,
  },
  {
    id: 27,
    seccion: ['Para Compartir'],
    plato: 'Ensaladilla Rusa',
    plato_ingles: 'Spanish Potatoe Salad',
    formato_tapa: 1.95,
    formato_media: 5.35,
    formato_racion: 8.35,
    alergenos: 'GLUTEN - HUEVO - PESCADO - LÁCTEO',
    top: false,
    new: false,
  },
  {
    id: 28,
    seccion: ['Para Compartir'],
    plato: 'Huevos Rotos Con Patatas Fritas, Jamón Y 2 Huevos Fritos',
    plato_ingles: 'Chips, Two Fried Eggs And Ham',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.5,
    alergenos: 'GLUTEN - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 28,
    seccion: ['Para Compartir'],
    plato: 'Huevos Rotos Con Patatas Fritas, Pata Al Horno Y 2 Huevos Fritos',
    plato_ingles: 'Chips, Two Fried Eggs And Roast Pork',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.5,
    alergenos: 'GLUTEN - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 29,
    seccion: ['Para Compartir'],
    plato: 'Huevos Estrellados Con Patatas Fritas Y 3 Huevos Fritos',
    plato_ingles: 'Chips And Three Fried Egg',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 7.45,
    alergenos: 'GLUTEN - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 30,
    seccion: ['Para Compartir'],
    plato: 'Revuelto Campero',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.45,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 40,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Pan Bao Negro - Con Langostino Tigre En Tempura, Verduras Y Salsa Japonesa',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.9,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 41,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Pan Bao Negro - Con Pollo Rebozado Al Estilo Japones, Rúcula, Salsa Con Especias Y  Curry',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 92,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Pan Bao Atún Rojo JC Mackintosh, Rodaja De Aguacate, Cebolla Morada Y Salsa Teriyaki',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.9,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: true,
  },
  {
    id: 42,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Quesadilla De Mezcla De Quesos - Rallado Blanco Y Cheddar',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 43,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Quesadilla "A Lo Vasayo" - Pata, Roquefort Y Cebolla Caramelizada',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 44,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Poke - Salmon, Edamame, Pepino, Aguacate, Sesamo, Mix Frutos Secos, Ponzu  Y Soja',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.65,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 45,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Poke - Atún, Edamame, Sesamo, Aguacate, Pepino, Zanahoria, Germinado, Ponzu Y Soja',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.65,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 46,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Gyozas - Empanadillas Japonesas De Pato - 4 Unidades',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 46,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Gyozas - Empanadillas Japonesas De Pollo - 4 Unidades',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'GLUTEN - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 46,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Gyozas - Empanadillas Japonesas De Gambas - 4 Unidades',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 47,
    seccion: ['Peques'],
    plato: 'Nugget Con Patatas Fritas',
    plato_ingles: 'Chicken Nugget With Fried Chips',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.55,
    alergenos: 'GLUTEN - HUEVO - LÁCTEOS',
    top: false,
    new: false,
  },
  {
    id: 48,
    seccion: ['Peques'],
    plato: 'Hot Dog Con La Salsa A Elegir Y Patatas Fritas',
    plato_ingles: 'Hot Dog With Sauce To Choose With Fried Chips',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.95,
    alergenos: 'GLUTEN - HUEVO - LÁCTEOS',
    top: false,
    new: false,
  },

  {
    id: 51,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Atún Rojo - UND',
    plato_ingles: 'TUNA',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.45,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 52,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Langostino Cocido - UND',
    plato_ingles: 'Cooked Shrimp',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESACDO - SOJA',
    top: false,
    new: false,
  },

  {
    id: 54,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Salmón- UND',
    plato_ingles: 'Cloocked Octupus',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 55,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Salmón Braseado - UND',
    plato_ingles: 'Roasted Salmon',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.95,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 56,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Anguila Asada - Und.',
    plato_ingles: 'Roasted Eel',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESCADO - SOJA - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 57,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Anguila Asada, Miel Y Sésamo - Und.',
    plato_ingles: 'Roasted Eel',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.85,
    alergenos: 'PESCADO - SOJA - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 58,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Atún - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Tuna',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 59,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Salmón - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Salmon',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 60,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Aguacate - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.95,
    alergenos: 'SOJA',
    top: false,
    new: false,
  },
  {
    id: 62,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Langostino - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.55,
    alergenos: 'SOJA - PESCADO',
    top: false,
    new: false,
  },

  {
    id: 62,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Wakame - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Wakame',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.95,
    alergenos: 'SOJA - SESAMO',
    top: false,
    new: false,
  },

  {
    id: 64,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Kentuky Maki - Pollo Frito, Mayonesa, Pepino Y Yakitori - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Fried Chicken, Mayonnaise, Cucumber And Yakitori',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: 'GLUTEN - SOJA - SESAMO - HUEVOS - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 65,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'California Maki - Aguacate, Cangrejo, Pepino, Mayonesa y Sésamo - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Fried Chicken, Mayonnaise, Cucumber And Yakitori',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: 'GLUTEN - SOJA - SESAMO - HUEVOS - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 66,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'El Rincón De Juan Maki - Atún, Tofu Frito, Mayonesa Y Tobiko - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'PESCADO - SOJA - SESAMO - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 67,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Delicia Maki - Langostino Cocido, Pepino y Philadelphia - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Cooked Prawn, Cucumber And Philadelphia',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'PESCADO - SESAMO - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 68,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Salmón Maki - Salmón, Aguacate y Pepino - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Salmon, Avocado and Cucumber',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'SOJA - PESCADO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 69,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Wakame Maki - Atún Wakame Y Tobiko - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Tuna, Wakame And Tobiko',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'SOJA - PESCADO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 70,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'New York Maki - Philadelphia, Salmón, Aguacate Y Sésamo - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Salmon, Avocado And Cheese',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'SOJA - PESCADO - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  // {
  //   id: 70,
  //   seccion: ['Nigiris - Maki Rolls'],
  //   plato:
  //     'Hawai Maki - Piña, Pepino, Salmón, Salsa Japonesa Y Wakame - Roll Con Varios Ingrediente Cortado En 8 Piezas',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 14.95,
  //   alergenos: 'SOJA - PESCADO - SESAMO - LACTEO',
  //   top: false,
  //   new: false,
  // },
  {
    id: 70,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Rainbow Maki - Cangrejo, Aguacate, Langostino En Tempura, Salsa Japonesa Y  Tobico - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.95,
    alergenos: 'SOJA - PESCADO - SESAMO - LACTEO',
    top: false,
    new: false,
  },

  {
    id: 71,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Almadraba Maki - Atún, Aguacate Y Tobiko En Tempura - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Tuna, Avocado And Tobiko Fried In Tempura',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'GLUTEN - SOJA - PESCADO - SESAMO - LACTEO - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 72,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Pimpi Maki - Salmón Y Aguacate En Tempura - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Salmon And Avocado Fried In Tempura',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'GLUTEN - SOJA - PESCADO - SESAMO - LACTEO - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 73,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Tropical Maki - Langostino En Tempura, Salsa Japonesa Y Aguacate - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'GLUTEN - SOJA - PESCADO - SESAMO - LACTEO - HUEVO',
    top: true,
    new: false,
  },
  {
    id: 74,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Hot Maki - Atún Rojo Picante, Aguacate Y Tofu - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: 'SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 75,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'UMAI Maki - Atún Rojo Y Langostino En Tempura, Con Salsa Agridulce, Cebolla Crujiente Y Salsa Japonesa',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 15.75,
    alergenos: 'GLUTEN - SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 76,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'SALMON CREAM Maki  - Salmón, Queso Crema, En Tempura, Con Agridulce, Salsa Japonesa Y Sesamo',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.75,
    alergenos: 'GLUTEN - SOJA - PESCADO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 76,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Gallega Maki  - Mostaza, Filete De Solomillo A La Parrilla, Coronado Con Cebolla Crujiente',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.55,
    alergenos: 'GLUTEN - SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 77,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Cerdo Ibérico Al Roquefort',
    plato_ingles: 'Grilled Iberian Pork Tenderloin With Roquefort Sauce',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.45,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },

  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Cerdo Ibérico A La Pimienta Verde',
    plato_ingles: 'Grilled Iberian Pork Tenderloin With Pepper Sauce',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.45,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato: 'Secreto Ibérico A La Parrilla',
    plato_ingles: 'Grilled Lean Iberian Pork Fillet',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 12,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Cerdo Ibérico A La Parrilla',
    plato_ingles: 'Grilled Iberian Pork Tenderloin',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Vaca A La Parrilla',
    plato_ingles: 'Grilled Sirloin Beef Steak',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 24.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 79,
    seccion: ['Carnes - Salsas'],
    plato: 'Brocheta De Solomillo De Cerdo Ibérico Con Verduras A La Parrilla',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 24.95,
    alergenos: '',
    top: false,
    new: false,
  },

  {
    id: 81,
    seccion: ['Mini Hamburguesas'],
    plato: 'Mini Hamburguesa De Solomillo De Vaca, Cheddar, Rúcula Y Mayonesa',
    plato_ingles: 'Sirloin Beef, Cheddar, Rocket And Mayonnaise',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.45,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: true,
    new: false,
  },
  {
    id: 82,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Solomillo De Vaca, Mostaza Y Cebolla Caramelizada',
    plato_ingles: 'Sirloin Beef, Mustar Sauce And Caramelized Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.45,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO - MOSTAZA',
    top: false,
    new: false,
  },
  {
    id: 83,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Solomillo De Vaca, Salsa Africana Y Cebolla Frita',
    plato_ingles: 'Sirloin Beef, Species Sauce And Fried Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.45,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },

  {
    id: 85,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Carne Madurada, Mostaza, Mayonesa, Cebolla Crujiente, Rodaja Tomate Y Cheddar',
    plato_ingles: 'Sirloin Beef',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 86,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Carne Madurada, 3 Quesos "Rallado, Cheddar Y Roquefort',
    plato_ingles: 'Sirloin Beef, 3 Cheese',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Mini Hamburguesas'],
    plato:
      'MINI BURGUER EL RINCON DE JUAN - Solomillo De Vaca, Picada Por Nosotros, Tomate, Pepinillo, Cebolla Morada, Nuestra Salsa Rosa, Cubierta De Salsa De Queso Cheddar',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.5,
    alergenos: 'GLUTEN - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 87,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 1 - 150 gramos de jugosa hamburguesa de solomillo de vaca, mayonesa, mostaza, lechuga, cebolla, tomate y cheddar, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 10.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 88,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 2 - 150 gramos de jugosa hamburguesa de solomillo de vaca, huevo frito, cebolla frita, mayonesa y rodaja de tomate, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 11.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 89,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 3 - Doble de 150 gramos de jugosa hamburguesa de solomillo de vaca, con cheddar, ketchup, pepinillo, mostaza y cebolla cruda, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 90,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 4 - 150 gramos de jugosa hamburguesa de solomillo de vaca, lechuga, cebolla cruda, cheddar, pepinillo y gaucha, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 10.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 91,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 5 - 150 gramos de jugosa hamburguesa de solomillo de vaca. Con cheddar, rúcula y mayonesa, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 10.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },

  {
    id: 93,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER DONNA - DE CARNE MADURADA - Con una maduración de 45 días, hemos elaborado ésta delicia. 150 gramos de carne madurada con un sabor intenso. Con Cheddar, Mostaza, Tomate, Mayonesa Y Cebolla Crujiente, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER LITTLE-JOHN - DE CARNE MADURADA - Con una maduración de 45 días, hemos elaborado ésta delicia. 150 gramos de carne madurada con un sabor intenso. 3 Quesos "Rallado, Cheddar Y Roquefort" , con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER DE WAGYU - 150 gramos de auténtica Carne De Wagyu Nacional, Con Bacon, Mayonesa, Cheddar y Lechuga, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 18.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER EL RINCON DE JUAN - 150 Gramos De Solomillo De Vaca, Picada Por Nosotros, Tomate, Pepinillo, Cebolla Morada, Nuestra Salsa Rosa, Cubierta De Salsa De Queso Cheddar Con Patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.5,
    alergenos: 'GLUTEN - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'MARY´S BURGUER   - Tiras De Crujiente Pechuga De Pollo En Tempura, Bacon, Mayonesa, Lechuga, Tomate A Rojada Con Patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.5,
    alergenos: 'GLUTEN - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER CHICKOA- Tiras De Crujiente Pechuga De Pollo En Tempura, Ali-Oli, Toque De Sriracha, Cheddar Y Lechuga',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.5,
    alergenos: 'GLUTEN - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Servicio Comensal 1,45 € Por Persona',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 1.45,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 12,
    seccion: ['Carnes - Salsas'],
    plato: 'Entrecot Madurado 45 Días',
    plato_ingles: 'Entrecot',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 26.0,
    alergenos: '',
    top: false,
    new: false,
  },

  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato:
      'Chateaubriand De Solomillo De Vaca, Cortado En Finos Filetes Para Hacer En La Mesa A Gusto Del Cliente',
    plato_ingles: 'To Make At The Table To Suit The Client',
    formato_tapa: 0,
    formato_media: 29.45,
    formato_racion: 44.95,
    alergenos: '',
    top: false,
    new: false,
  },

  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato:
      'Bol De Salsas - Mayonesa, Ketchup, Pimienta Verde, Roquefort, Ali-Oli, Gaucha, Africano, Agridulce, Barbacoa - UND ',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 0.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 79,
    seccion: ['Carnes - Salsas'],
    plato: 'Bol De Salsas - Picante Sriracha - Mostaza - Japonesa - UND ',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 1.55,
    alergenos: '',
    top: false,
    new: false,
  },
];
