import { Comida } from '../interfaces/comida';

export const COMIDAS: Comida[] = [
  //   {
  //     id: 1,
  //     seccion: ['TOP 5'],
  //     plato: 'prueba',
  //     plato_ingles: 'Iberian Ham',
  //     formato_tapa: 2.95,
  //     formato_media: 0,
  //     formato_racion: 16.95,
  //     alergenos: 'LÁCTEOS',
  //     top: false,
  //     new: false,
  //   },
  {
    id: 2,
    seccion: ['Top 5', 'Jamón Ibérico De Bellota Y Corte'],
    plato: 'Jamón Ibérico De Bellota',
    plato_ingles: 'Iberian Ham',
    formato_tapa: 0,
    formato_media: 10.95,
    formato_racion: 19.95,
    alergenos: '',
    top: true,
    new: false,
  },
  {
    id: 3,
    seccion: ['Verde Que Te Quiero Verde'],
    plato:
      'Ensalada Mixta Con Lechuga, Cebolla, Atún, Tomate Y Zanahoria Rallada -- Ya Está Aliñada',
    plato_ingles: 'Mixta: Lettuce, Tomato, Onion, Cucumber, Carrot And Tuna',
    formato_tapa: 0,
    formato_media: 6.45,
    formato_racion: 8.45,
    alergenos: 'PESCADO',
    top: false,
    new: true,
  },

  {
    id: 4,
    seccion: ['Para Compartir'],
    plato:
      'Ensaladilla De Patatas, Zanahoria, Dados De Atún JC Mackintosh, Mayonesa Con Ajo Confitado Y Huevo Frito En Virgen Extra',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 9.45,
    formato_racion: 12.95,
    alergenos: 'PESCADO - HUEVOS - LACTEOS - CRUSTÁCEOS',
    top: true,
    new: false,
  },
  {
    id: 5,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Pan Bao Blanco - Con Jarrete, Verduras Y Salsa Yakitori',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.55,
    alergenos: 'GLUTEN - LACTEO - HUEVO',
    top: false,
    new: false,
  },

  {
    id: 9,
    seccion: ['Peques'],
    plato: 'Croquetas Caseras 5 Und. De Jamón Ibérico Con Patatas Fritas',
    plato_ingles: '5 Ham Croquette With Fried Chips',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.55,
    alergenos: 'HUEVO - SOJA',
    top: false,
    new: false,
  },
  // {
  //   id: 10,
  //   seccion: ['Nigiris - Maki Rolls'],
  //   plato: 'Nigiri De Solomillo De Vaca Y Foie Flambeado - 2 Und',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 6.45,
  //   alergenos: 'SOJA',
  //   top: false,
  //   new: false,
  // },
  {
    id: 12,
    seccion: ['Top 5', 'Carnes - Salsas'],
    plato: 'Entrecot Madurado 45 Días',
    plato_ingles: 'Entrecot',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 26.00,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 12,
    seccion: ['Top 5', 'Carnes - Salsas'],
    plato: 'Chuleton Madurado 45 Días De Retinto - Precio Por Kilo',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 45.00,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 12,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Cerdo Ibérico A La Parrilla',
    plato_ingles: 'Grilled Iberian Pork Tenderloin',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.45,
    alergenos: '',
    top: false,
    new: false,
  },

  {
    id: 14,
    seccion: ['Mini Hamburguesas'],
    plato: 'Mini Hamburguesa De Atún Rojo Con Salsa Tártara',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: '',
    top: false,
    new: false,
  },

  {
    id: 16,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Jamón Ibérico De Bellota Y Pata Al Horno Con AOVE y Sal',
    plato_ingles: 'Iberian Ham and Roast Pork And Extra Virgin Olive Oil',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.95,
    alergenos: 'LÁCTEOS',
    top: false,
    new: false,
  },
  {
    id: 17,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato:
      'Huevos Con Jamón Ibérico De Bellota -  Con Patatas, 3 Huevos De Campo y Jamón De Ibérico De Bellota Cortado A Cuchillo',
    plato_ingles: 'Chips, Three Fried Eggs And Iberian Ham',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.95,
    alergenos: 'GLUTEN',
    top: false,
    new: true,
  },
  {
    id: 18,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Pata De Cerdo Al Horno Con AOVE y Sal',
    plato_ingles: 'Roast Pork And Extra Virgin Olive Oil',
    formato_tapa: 2.5,
    formato_media: 7.45,
    formato_racion: 9.75,
    alergenos: 'GLUTEN',
    top: false,
    new: false,
  },
  {
    id: 18,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Queso Curado De Oveja',
    plato_ingles: 'Sheep Cheese',
    formato_tapa: 2.5,
    formato_media: 7.45,
    formato_racion: 9.75,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 18,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Jamón Ibérico De Bellota Y Queso Curado De Oveja',
    plato_ingles: 'Iberian Ham And Sheep´s Cheese',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.95,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 19,
    seccion: ['Top 5','Verde Que Te Quiero Verde'],
    plato: 'Pimientos De Padrón Fritos En Virgen Extra',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.95,
    alergenos: 'GLUTEN',
    top: false,
    new: false,
  },
  {
    id: 20,
    seccion: ['Verde Que Te Quiero Verde'],
    plato:
      'Ensalada El Rincón De Juan Con Lechuga, Tomate, Jamón A Taquitos y Cheddar --- Ya Está Aliñada',
    plato_ingles: 'El Rincón De Juan - Lettuce, Tomato, Ham And Cheddar Cheese',
    formato_tapa: 0,
    formato_media: 7.45,
    formato_racion: 9.45,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 21,
    seccion: ['Verde Que Te Quiero Verde'],
    plato: 'Espárragos Verdes Al Ajillo',
    plato_ingles:
      'Grilled Green Asparagus With Garlic And Extra Virgin Olive Oil',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 7.25,
    alergenos: '',
    top: true,
    new: false,
  },
  {
    id: 22,
    seccion: ['Verde Que Te Quiero Verde'],
    plato: 'Tomate Con Atún, AOVE y Perejil',
    plato_ingles: 'Tomato, Tuna, Parsley  And Extra Virgin Olive Oil',
    formato_tapa: 0,
    formato_media: 5.45,
    formato_racion: 7.45,
    alergenos: 'PESCADO',
    top: false,
    new: false,
  },
  {
    id: 23,
    seccion: ['Para Compartir'],
    plato: 'Gambones A La Plancha',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.85,
    alergenos: 'PESCADO',
    top: false,
    new: false,
  },
  {
    id: 24,
    seccion: ['Top 5','Para Compartir'],
    plato: 'Tartar De Atún Rojo, Cebolla, Base Aguacate Y Soja',
    plato_ingles: 'Tuna Tartar',
    formato_tapa: 8.5,
    formato_media: 0,
    formato_racion: 15.85,
    alergenos: 'GLUTEN - PESCADO - SOJA',
    top: true,
    new: false,
  },
  {
    id: 25,
    seccion: ['Para Compartir'],
    plato: 'Paté de perdiz',
    plato_ingles: 'Partridge Pate And Caramelized Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 8.55,
    alergenos: 'GLUTEN - LÁCTEO',
    top: false,
    new: false,
  },
  {
    id: 26,
    seccion: ['Para Compartir'],
    plato: 'Paté De Boletus Y Queso',
    plato_ingles: 'Partridge Pate And Caramelized Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 8.95,
    alergenos: 'GLUTEN - LÁCTEO',
    top: false,
    new: false,
  },
  {
    id: 27,
    seccion: ['Para Compartir'],
    plato: 'Ensaladilla Rusa',
    plato_ingles: 'Spanish Potatoe Salad',
    formato_tapa: 1.95,
    formato_media: 5.35,
    formato_racion: 8.35,
    alergenos: 'GLUTEN - HUEVO - PESCADO - LÁCTEO',
    top: false,
    new: false,
  },
  {
    id: 28,
    seccion: ['Para Compartir'],
    plato: 'Huevos Rotos Con Patatas Fritas, Jamón Y 2 Huevos Fritos',
    plato_ingles: 'Chips, Two Fried Eggs And Ham',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: 'GLUTEN - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 28,
    seccion: ['Para Compartir'],
    plato: 'Huevos Rotos Con Patatas Fritas, Pata Al Horno Y 2 Huevos Fritos',
    plato_ingles: 'Chips, Two Fried Eggs And Roast Pork',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: 'GLUTEN - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 29,
    seccion: ['Para Compartir'],
    plato: 'Huevos Estrellados Con Patatas Fritas Y 3 Huevos Fritos',
    plato_ingles: 'Chips And Three Fried Egg',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.45,
    alergenos: 'GLUTEN - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 30,
    seccion: ['Para Compartir'],
    plato: 'Revuelto Campero',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 9.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 40,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Pan Bao Negro - Con Langostino En Tempura, Verduras Y Salsa Japonesa',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 41,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Pan Bao Negro - Con Pollo Rebozado Al Estilo Japones, Rúcula, Salsa Con Especias Y Curry',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 42,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Quesadilla De Mezcla De Quesos - Rallado Blanco Y Cheddar',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 43,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Quesadilla "A Lo Vasayo" - Pata, Roquefort Y Cebolla Caramelizada',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 44,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Poke - Salmon, Edamame, Pepino, Aguacate, Sesamo, Mix Frutos Secos, Ponzu  Y Soja',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.65,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 45,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato:
      'Poke - Atún, Edamame, Sesamo, Aguacate, Pepino, Zanahoria, Germinado, Ponzu Y Soja',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.65,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  // {
  //   id: 46,
  //   seccion: ['Baos - Quesadillas - Poke - Gyozas'],
  //   plato: 'Gyozas De Pato - 4 Unidades',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 6.95,
  //   alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
  //   top: false,
  //   new: false,
  // },
  {
    id: 46,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Gyozas De Pollo - 4 Unidades',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'GLUTEN - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 46,
    seccion: ['Baos - Quesadillas - Poke - Gyozas'],
    plato: 'Gyozas De Gambas - 4 Unidades',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.95,
    alergenos: 'GLUTEN - PESCADO - SOJA - FRUTOS CON CASCARA - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 47,
    seccion: ['Peques'],
    plato: 'Finger De Pollo Con Patatas Fritas',
    plato_ingles: 'Chicken Finger With Fried Chips',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.55,
    alergenos: 'GLUTEN - HUEVO - LÁCTEOS',
    top: false,
    new: false,
  },
  {
    id: 48,
    seccion: ['Peques'],
    plato: 'Hot Dog Con La Salsa A Elegir Y Patatas Fritas',
    plato_ingles: 'Hot Dog With Sauce To Choose With Fried Chips',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.95,
    alergenos: 'GLUTEN - HUEVO - LÁCTEOS',
    top: false,
    new: false,
  },

  {
    id: 51,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Atún Rojo - UND',
    plato_ingles: 'TUNA',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.45,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 52,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Langostino Cocido - UND',
    plato_ingles: 'Cooked Shrimp',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESACDO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 53,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Pulpo - UND',
    plato_ingles: 'Coocked Octupus',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESACDO - SOJA',
    top: false,
    new: false,
  },

  {
    id: 54,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Salmón- UND',
    plato_ingles: 'Cloocked Octupus',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 55,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Salmón Braseado - 3 Und.',
    plato_ingles: 'Roasted Salmon',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 7.95,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 56,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Anguila Asada - Und.',
    plato_ingles: 'Roasted Eel',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.45,
    alergenos: 'PESCADO - SOJA - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 57,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Nigiri De Anguila Asada, Miel Y Sésamo - Und.',
    plato_ingles: 'Roasted Eel',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.85,
    alergenos: 'PESCADO - SOJA - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 58,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Atún - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Tuna',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.95,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 59,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Salmón - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Salmon',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 5.95,
    alergenos: 'PESCADO - SOJA',
    top: false,
    new: false,
  },
  {
    id: 60,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Aguacate - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.95,
    alergenos: 'SOJA',
    top: false,
    new: false,
  },
  {
    id: 61,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Tofu Frito - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Fried Tofu',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 4.95,
    alergenos: 'SOJA - SESAMO',
    top: false,
    new: true,
  },
  {
    id: 62,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Langostino - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.55,
    alergenos: 'SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 62,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Pulpo - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Octopus',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 6.55,
    alergenos: 'SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 62,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Wakame - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Wakame',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'SOJA - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 63,
    seccion: ['Nigiris - Maki Rolls'],
    plato: 'Hosomaki De Pepino - Roll De 1 Ingrediente Cortado En 6 Piezas',
    plato_ingles: 'Cucumber',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'SOJA - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 64,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Kentuky Maki - Pollo Frito, Mayonesa, Pepino Y Yakitori - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Fried Chicken, Mayonnaise, Cucumber And Yakitori',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 12.95,
    alergenos: 'GLUTEN - SOJA - SESAMO - HUEVOS - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 65,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'California Maki - Aguacate, Cangrejo, Pepino, Mayonesa y Sésamo - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Fried Chicken, Mayonnaise, Cucumber And Yakitori',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 11.95,
    alergenos: 'GLUTEN - SOJA - SESAMO - HUEVOS - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 66,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'El Rincón De Juan Maki - Atún, Tofu Frito, Mayonesa Y Tobiko - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'PESCADO - SOJA - SESAMO - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 67,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Delicia Maki - Langostino Cocido, Pepino y Philadelphia - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Cooked Prawn, Cucumber And Philadelphia',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'PESCADO - SESAMO - LACTEOS',
    top: false,
    new: false,
  },
  {
    id: 68,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Salmón Maki - Salmón, Aguacate y Pepino - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Salmon, Avocado and Cucumber',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'SOJA - PESCADO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 69,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Wakame Maki - Atún Wakame Y Tobiko - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Tuna, Wakame And Tobiko',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'SOJA - PESCADO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 70,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'New York Maki - Philadelphia, Salmón, Aguacate Y Sésamo - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Salmon, Avocado And Cheese',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.95,
    alergenos: 'SOJA - PESCADO - SESAMO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 71,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Almadraba Maki - Atún, Aguacate Y Tobiko En Tempura - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Tuna, Avocado And Tobiko Fried In Tempura',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'GLUTEN - SOJA - PESCADO - SESAMO - LACTEO - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 72,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Pimpi Maki - Salmón Y Aguacate En Tempura - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Salmon And Avocado Fried In Tempura',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'GLUTEN - SOJA - PESCADO - SESAMO - LACTEO - HUEVO',
    top: false,
    new: false,
  },
  {
    id: 73,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Tropical Maki - Langostino En Tempura, Salsa Japonesa Y Aguacate - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'GLUTEN - SOJA - PESCADO - SESAMO - LACTEO - HUEVO',
    top: true,
    new: false,
  },
  {
    id: 74,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Hot Maki - Atún Rojo Picante, Aguacate Y Tofu - Roll Con Varios Ingrediente Cortado En 8 Piezas',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.55,
    alergenos: 'SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 75,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'UMAI Maki - Atún Rojo Y Langostino En Tempura, Con Salsa Agridulce, Cebolla Crujiente Y Salsa Japonesa',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 15.75,
    alergenos: 'GLUTEN - SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 76,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'SALMON CREAM Maki  - Salmón, Queso Crema, En Tempura, Con Agridulce, Salsa Japonesa Y Sesamo',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.75,
    alergenos: 'GLUTEN - SOJA - PESCADO - LACTEO',
    top: false,
    new: false,
  },
  {
    id: 76,
    seccion: ['Nigiris - Maki Rolls'],
    plato:
      'Gallega Maki  - Mostaza, Filete De Solomillo A La Parrilla, Coronado Con Cebolla Crujiente',
    plato_ingles: 'Prawn Fried In Tempura, Japanese Sauce And Avocado',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 13.55,
    alergenos: 'GLUTEN - SOJA - PESCADO',
    top: false,
    new: false,
  },
  {
    id: 77,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Cerdo Ibérico Al Roquefort',
    plato_ingles: 'Grilled Iberian Pork Tenderloin With Roquefort Sauce',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Cerdo Ibérico A La Pimienta Verde',
    plato_ingles: 'Grilled Iberian Pork Tenderloin With Pepper Sauce',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.45,
    alergenos: 'LACTEO',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato: 'Secreto Ibérico A La Parrilla',
    plato_ingles: 'Grilled Lean Iberian Pork Fillet',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato: 'Solomillo De Vaca A La Parrilla',
    plato_ingles: 'Grilled Sirloin Beef Steak',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 24.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato:
      'Chateaubriand De Solomillo De Vaca, Cortado En Finos Filetes Para Hacer En La Mesa A Gusto Del Cliente',
    plato_ingles: 'To Make At The Table To Suit The Client',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 39.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 78,
    seccion: ['Carnes - Salsas'],
    plato:
      'Bol De Salsas - Mayonesa, Ketchup, Pimienta Verde, Roquefort, Ali-Oli, Gaucha, Africano, Agridulce, Barbacoa - UND ',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 0.95,
    alergenos: '',
    top: false,
    new: false,
  },
  {
    id: 79,
    seccion: ['Carnes - Salsas'],
    plato: 'Bol De Salsas - Picante Sriracha - Mostaza - Japonesa - UND ',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 1.55,
    alergenos: '',
    top: false,
    new: false,
  },

  {
    id: 81,
    seccion: ['Mini Hamburguesas'],
    plato: 'Mini Hamburguesa De Solomillo De Vaca, Cheddar, Rúcula Y Mayonesa',
    plato_ingles: 'Sirloin Beef, Cheddar, Rocket And Mayonnaise',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: true,
    new: false,
  },
  {
    id: 82,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Solomillo De Vaca, Mostaza Y Cebolla Caramelizada',
    plato_ingles: 'Sirloin Beef, Mustar Sauce And Caramelized Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO - MOSTAZA',
    top: false,
    new: false,
  },
  {
    id: 83,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Solomillo De Vaca, Salsa Africana Y Cebolla Frita',
    plato_ingles: 'Sirloin Beef, Species Sauce And Fried Onion',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 2.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  // {
  //   id: 84,
  //   seccion: ['Mini Hamburguesas'],
  //   plato:
  //     'Mini Hamburguesa De Solomillo De Vaca, Queso Viejo, Foie Y Mermelada',
  //   plato_ingles: 'Sirloin Beef, Old Cheese, Foie Y Marmalade',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 4.95,
  //   alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
  //   top: false,
  //   new: false,
  // },
  {
    id: 85,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Carne Madurada, Mostaza, Mayonesa, Cebolla Crujiente, Rodaja Tomate Y Cheddar',
    plato_ingles: 'Sirloin Beef',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 86,
    seccion: ['Mini Hamburguesas'],
    plato:
      'Mini Hamburguesa De Carne Madurada, 3 Quesos "Rallado, Cheddar Y Roquefort',
    plato_ingles: 'Sirloin Beef, 3 Cheese',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 3.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 87,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 1 - 150 gramos de jugosa hamburguesa de solomillo de vaca, mayonesa, mostaza, lechuga, cebolla, tomate y cheddar, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 10.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 88,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 2 - 150 gramos de jugosa hamburguesa de solomillo de vaca, huevo frito, cebolla frita, mayonesa y rodaja de tomate, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 11.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 89,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 3 - Doble de 150 gramos de jugosa hamburguesa de solomillo de vaca, con cheddar, ketchup, pepinillo, mostaza y cebolla cruda, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 16.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 90,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 4 - 150 gramos de jugosa hamburguesa de solomillo de vaca, lechuga, cebolla cruda, cheddar, pepinillo y gaucha, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 10.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 91,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER GOURMET 5 - 150 gramos de jugosa hamburguesa de solomillo de vaca. Con cheddar, rúcula y mayonesa, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 10.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  // {
  //   id: 92,
  //   seccion: ['Hamburguesas Gourmet'],
  //   plato:
  //     'BURGUER GOURMET 6 - 150 gramos de jugosa hamburguesa de solomillo de vaca. Con queso curado, foie y mermelada, con patatas',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 10.55,
  //   alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
  //   top: false,
  //   new: false,
  // },
  {
    id: 93,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER DONNA - DE CARNE MADURADA - Con una maduración de 45 días, hemos elaborado ésta delicia. 150 gramos de carne madurada con un sabor intenso. Con Cheddar, Mostaza, Tomate, Mayonesa Y Cebolla Crujiente, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER LITTLE-JOHN - DE CARNE MADURADA - Con una maduración de 45 días, hemos elaborado ésta delicia. 150 gramos de carne madurada con un sabor intenso. 3 Quesos "Rallado, Cheddar Y Roquefort" , con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 14.55,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER DE WAGYU - 150 gramos de auténtica Carne De Wagyu Nacional, Con Bacon, Mayonesa, Cheddar y Lechuga, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 18.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  {
    id: 94,
    seccion: ['Hamburguesas Gourmet'],
    plato:
      'BURGUER DE WAGYU - 150 gramos de auténtica Carne De Wagyu Nacional, Con Bacon, Mayonesa, Cheddar y Lechuga, con patatas',
    plato_ingles: '',
    formato_tapa: 0,
    formato_media: 0,
    formato_racion: 18.95,
    alergenos: 'GLUTEN - HUEVO - LACTEO - SESAMO',
    top: false,
    new: false,
  },
  // {
  //   id: 94,
  //   seccion: ['Top 5'],
  //   plato: 'Rosada Frita',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 8.5,
  //   formato_racion: 14.5,
  //   alergenos: 'GLUTEN',
  //   top: true,
  //   new: true,
  // },
  // {
  //   id: 94,
  //   seccion: ['Top 5'],
  //   plato: 'Churrasco De Pollo',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 10.9,
  //   alergenos: '',
  //   top: true,
  //   new: true,
  // },
  // {
  //   id: 94,
  //   seccion: ['Top 5'],
  //   plato: 'Mini Rollito De Verduras',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 2.75,
  //   alergenos: 'GLUTEN - SOJA',
  //   top: true,
  //   new: true,
  // },
  // {
  //   id: 94,
  //   seccion: ['Top 5'],
  //   plato: 'Sashimi De Atún Rojo JC Mackintosh',
  //   plato_ingles: '',
  //   formato_tapa: 0,
  //   formato_media: 0,
  //   formato_racion: 16.50,
  //   alergenos: '',
  //   top: true,
  //   new: true,
  // },
  {
    id: 95,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Caña De Lomo Ibérica',
    plato_ingles: '',
    formato_tapa: 2.95,
    formato_media: 6.9,
    formato_racion: 11.9,
    alergenos: '',
    top: true,
    new: true,
  },
  {
    id: 96,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Salchichón Ibérico',
    plato_ingles: '',
    formato_tapa: 2.25,
    formato_media: 5.9,
    formato_racion: 8.9,
    alergenos: '',
    top: true,
    new: true,
  },
  {
    id: 97,
    seccion: ['Jamón Ibérico De Bellota Y Corte'],
    plato: 'Chorizo Ibérico',
    plato_ingles: '',
    formato_tapa: 2.25,
    formato_media: 5.9,
    formato_racion: 8.9,
    alergenos: '',
    top: true,
    new: true,
  },
];

// GLUTEN 1 / CRUSTÁCEOS 2 / HUEVOS 3 / PESCADO 4 /CACAHUETES 5 /
// SOJA 6 / LÁCTEOS 7 / FRUTOS DE CÁSCARA 8 / APIO 9 / MOSTAZA 10 / GRANOS DE
// SÉSAMO 11 / DIÓXIDO DE AZUFRE Y SULFITOS 12 / ALTRAMUCES 13 / MOLUSCOS 14 /

/**

// GLUTEN 1 / CRUSTÁCEOS 2 / HUEVOS 3 / PESCADO 4 /CACAHUETES 5 /
// SOJA 6 / LÁCTEOS 7 / FRUTOS DE CÁSCARA 8 / APIO 9 / MOSTAZA 10 / GRANOS DE
// SÉSAMO 11 / DIÓXIDO DE AZUFRE Y SULFITOS 12 / ALTRAMUCES 13 / MOLUSCOS 14 /

'Hamburguesas Gourmet' => array (
            array ( 120, 'BURGUER GOURMET 1', '150 gramos de jugosa hamburguesa de solomillo de vaca, mayonesa, mostaza, lechuga, cebolla, tomate y cheddar, con patatas ' ,   '' ,   '10.50', '[1] - [3] - [7] - [11]'),
            array ( 121, 'BURGUER GOURMET 2', '150 gramos de jugosa hamburguesa de solomillo de vaca, huevo frito, cebolla frita, mayonesa y rodaja de tomate, con patatas ' ,   '' ,   '11.50', '[1] - [3] - [7] - [11]'),
            array ( 122, 'BURGUER GOURMET 3', 'Doble de 150 gramos de jugosa hamburguesa de solomillo de vaca, con cheddar, ketchup, pepinillo, mostaza y cebolla cruda, con patatas ' ,   '' ,   '16.45', '[1] - [3] - [7] - [11]'),
            array ( 123, 'BURGUER GOURMET 4', '150 gramos de jugosa hamburguesa de solomillo de vaca, lechuga, cebolla cruda, cheddar, pepinillo y gaucha, con patatas ' ,  '' ,   '10.50', '[1] - [3] - [7] - - [10] - [11]'),
            array ( 124, 'BURGUER GOURMET 5', '150 gramos de jugosa hamburguesa de solomillo de vaca. Con cheddar, rúcula y  mayonesa, con patatas ',   '' ,   '10.50', '[1] - [3] - [7] - [11]'),
            array ( 125, 'BURGUER GOURMET 6', '150 gramos de jugosa hamburguesa de solomillo de vaca. Con queso curado, foie y  mermelada, con patatas ',   '' ,   '15.50', '[1] - [3] - [7] - [11]'),
            array ( 126, 'BURGUER DONNA - DE CARNE MADURADA' , 'Con una maduración de 45 días, hemos elaborado ésta delicia. 150 gramos de carne madurada con un sabor intenso. Con Cheddar, Mostaza, Tomate, Mayonesa Y Cebolla Crujiente, con patatas ',   '' ,   '14.50', '[1] - [3] - [7] - [11]'),
            array ( 127, 'BURGUER LITTLE-JOHN - DE CARNE MADURADA' , 'Con una maduración de 45 días, hemos elaborado ésta delicia. 150 gramos de carne madurada con un sabor intenso. 3 Quesos "Rallado, Cheddar Y Roquefort" , con patatas ',   '' ,   '14.50', '[1] - [3] - [7] - [11]'),
            array ( 128, 'BURGUER DE WAGYU' , '150 gramos de auténtica Carne De Wagyu Nacional, Con Bacon, Mayonesa, Cheddar y Lechuga, con patatas ',   '' ,   '18.90', '[1] - [3] - [7] - [11]'),
)
// GLUTEN 1 / CRUSTÁCEOS 2 / HUEVOS 3 / PESCADO 4 /CACAHUETES 5 /
// SOJA 6 / LÁCTEOS 7 / FRUTOS DE CÁSCARA 8 / APIO 9 / MOSTAZA 10 / GRANOS DE
// SÉSAMO 11 / DIÓXIDO DE AZUFRE Y SULFITOS 12 / ALTRAMUCES 13 / MOLUSCOS 14 /
)
?>
<?php 
$indice = 0; 
?>
 * 
 * 
 * 
 * 
 */
