import { Vino } from '../interfaces/vino';

export const VINOS: Vino[] = [
  {
    id: 1,
    seccion: ['Vino Por Copas', 'Rioja'],
    vino: 'Choza',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: 'Rioja',
    precio_copa: 2.9,
    precio_botella: 15.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 2,
    seccion: ['Vino Por Copas', 'Ribera Del Duero'],
    vino: 'Balbás 5 Meses',
    envejecimiento: 'Roble',
    anada: 2020,
    uvas: ['tempranillo'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 2.9,
    precio_botella: 16.9,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 3,
    seccion: ['Ribera Del Duero'],
    vino: 'Balbás 18 Meses',
    envejecimiento: 'Crianza',
    anada: 2016,
    uvas: ['tempranillo'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 4.9,
    precio_botella: 26.9,
    top: false,
    new: true,
    last: false,
  },
  {
    id: 4,
    seccion: ['Ribera Del Duero'],
    vino: 'Carramimbre',
    envejecimiento: 'Crianza',
    anada: 2018,
    uvas: ['tempranillo', 'cabernet sauvignon'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 3.3,
    precio_botella: 21.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 5,
    seccion: ['Ribera Del Duero'],
    vino: 'Altamimbre',
    envejecimiento: 'Cosecha',
    anada: 2017,
    uvas: ['tempranillo'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 5.5,
    precio_botella: 38.0,
    top: false,
    new: true,
    last: false,
  },
  {
    id: 6,
    seccion: ['Otras DO'],
    vino: 'Abadia Retuerta Selección Especial',
    envejecimiento: 'Autor',
    anada: 2017,
    uvas: ['tempranillo', 'syrah', 'cabernet sauvignon'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 28.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 7,
    seccion: ['Franceses Y Australiano'],
    vino: 'Jacob´s Creek Classic',
    envejecimiento: 'Autor',
    anada: 2018,
    uvas: ['syrah', 'cabernet sauvignon'],
    denominacion_origen: 'Australia',
    precio_copa: 0,
    precio_botella: 19.5,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 7,
    seccion: ['Champagne Y Cava'],
    vino: 'MUMM',
    envejecimiento: 'brut',
    anada: 2022,
    uvas: ['tempranillo'],
    denominacion_origen: 'Francia',
    precio_copa: 0,
    precio_botella: 49.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 7,
    seccion: ['Blancos Y Rosados'],
    vino: 'Verdejo',
    envejecimiento: 'Del Año',
    anada: 2022,
    uvas: ['verdejo'],
    denominacion_origen: 'Rueda',
    precio_copa: 2.9,
    precio_botella: 18.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 7,
    seccion: ['Blancos Y Rosados'],
    vino: 'Semidulce',
    envejecimiento: 'Del Año',
    anada: 2022,
    uvas: ['viura'],
    denominacion_origen: 'Rueda',
    precio_copa: 3.0,
    precio_botella: 18.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 7,
    seccion: ['Blancos Y Rosados'],
    vino: 'Yllera 5.5',
    envejecimiento: 'Del Año',
    anada: 2022,
    uvas: ['frizzante'],
    denominacion_origen: '',
    precio_copa: 3.0,
    precio_botella: 18.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 10,
    seccion: ['Ribera Del Duero'],
    vino: 'Carmelo Rodero 9 Meses',
    envejecimiento: 'cosecha',
    anada: 2020,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 19.95,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 10,
    seccion: ['Ribera Del Duero'],
    vino: 'Cepa 21',
    envejecimiento: 'cosecha',
    anada: 2017,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 27.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 10,
    seccion: ['Ribera Del Duero'],
    vino: 'Pesquera',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 27.5,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 10,
    seccion: ['Vino Por Copas', 'Ribera Del Duero'],
    vino: 'Emilio Moro',
    envejecimiento: 'Cosecha',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 4.95,
    precio_botella: 28.5,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Carmelo Rodero',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo', 'cabernet sauvignon'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 28.95,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Matarromera',
    envejecimiento: 'Crianza',
    anada: 2018,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 29.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Arzuaga',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo', 'cabernet sauvignon'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 29.2,
    top: false,
    new: true,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Malleolus',
    envejecimiento: 'Cosecha',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 38.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Tomas Postigo',
    envejecimiento: 'Cosecha',
    anada: 2018,
    uvas: ['tempranillo', 'merlot', 'cabernet sauvignon', 'merlot', 'malbec'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 38.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Hacienda Monasterio',
    envejecimiento: 'Cosecha',
    anada: 2019,
    uvas: ['tempranillo', 'cabernet sauvignon', 'merlot'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 39.0,
    top: false,
    new: false,
    last: false,
  },
  // {
  //   id: 20,
  //   seccion: ['Ribera Del Duero'],
  //   vino: 'Carmelo Rodero',
  //   envejecimiento: 'Reserva',
  //   anada: 2018,
  //   uvas: ['tempranillo', 'cabernet sauvignon'],
  //   denominacion_origen: '',
  //   precio_copa: 0,
  //   precio_botella: 39.0,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Valbuena 5º Año - Vega Sicilia',
    envejecimiento: 'cosecha',
    anada: 2016,
    uvas: ['tempranillo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 149.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Ribera Del Duero'],
    vino: 'Unico - Vega Sicilia',
    envejecimiento: 'cosecha',
    anada: 2010,
    uvas: ['tempranillo', 'cabernet sauvignon'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 349.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 20,
    seccion: ['Rioja'],
    vino: 'Castillo De Ygay',
    envejecimiento: 'Gran Reserva',
    anada: 2010,
    uvas: ['tempranillo', 'mazuelo'],
    denominacion_origen: '',
    precio_copa: 0,
    precio_botella: 320.0,
    top: false,
    new: false,
    last: false,
  },
  // {
  //   id: 20,
  //   seccion: ['Otras DO'],
  //   vino: 'Abadia Retuerta Selección Especial',
  //   envejecimiento: 'Autor',
  //   anada: 2017,
  //   uvas: ['tempranillo', 'syrah', 'cabernet sauvignon'],
  //   denominacion_origen: '',
  //   precio_copa: 0,
  //   precio_botella: 28.0,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  {
    id: 20,
    seccion: ['Otras DO'],
    vino: 'Matsu El Viejo',
    envejecimiento: 'Autor',
    anada: 2017,
    uvas: ['tempranillo'],
    denominacion_origen: 'Toro',
    precio_copa: 0,
    precio_botella: 34.0,
    top: false,
    new: false,
    last: false,
  },
  // {
  //   id: 40,
  //   seccion: ['Otras DO'],
  //   vino: 'San Roman',
  //   envejecimiento: 'Autor',
  //   anada: 2016,
  //   uvas: ['tempranillo'],
  //   denominacion_origen: 'Toro',
  //   precio_copa: 0,
  //   precio_botella: 37.0,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  {
    id: 41,
    seccion: ['Otras DO'],
    vino: 'San Roman',
    envejecimiento: 'Autor',
    anada: 2016,
    uvas: ['tempranillo'],
    denominacion_origen: 'Toro',
    precio_copa: 0,
    precio_botella: 37.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 41,
    seccion: ['Otras DO'],
    vino: 'El Veneno - Pepe Mendoza',
    envejecimiento: 'Cosecha',
    anada: 2018,
    uvas: ['monastrel'],
    denominacion_origen: 'Alicante',
    precio_copa: 0,
    precio_botella: 40.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 42,
    seccion: ['Otras DO'],
    vino: 'Val De La Osa',
    envejecimiento: 'Autor',
    anada: 2017,
    uvas: ['mencia'],
    denominacion_origen: 'Bierzo',
    precio_copa: 0,
    precio_botella: 26.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 42,
    seccion: ['Otras DO'],
    vino: 'Aurea - Pittacum',
    envejecimiento: 'Autor',
    anada: 2012,
    uvas: ['mencia'],
    denominacion_origen: 'Bierzo',
    precio_copa: 0,
    precio_botella: 45.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 43,
    seccion: ['Otras DO'],
    vino: 'Alas De Frontonio',
    envejecimiento: 'Autor',
    anada: 2016,
    uvas: ['garnacha'],
    denominacion_origen: 'Valdejalon',
    precio_copa: 0,
    precio_botella: 45.0,
    top: false,
    new: false,
    last: false,
  },

  {
    id: 51,
    seccion: ['Franceses Y Australiano'],
    vino: 'Le Pigeoulet Selon Frederic & Daniel Brunier Vaucluse',
    envejecimiento: 'Autor',
    anada: 2018,
    uvas: ['garnacha', 'syrah'],
    denominacion_origen: 'Frances',
    precio_copa: 0,
    precio_botella: 24.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 51,
    seccion: ['Franceses Y Australiano'],
    vino: 'Michel Lynch Nature Bordeaux',
    envejecimiento: 'Autor',
    anada: 2019,
    uvas: ['merlot'],
    denominacion_origen: 'Frances',
    precio_copa: 0,
    precio_botella: 22.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 51,
    seccion: ['Franceses Y Australiano'],
    vino: 'Cotes Du Rhone Reserve',
    envejecimiento: 'Reserva',
    anada: 2018,
    uvas: [],
    denominacion_origen: 'Frances',
    precio_copa: 0,
    precio_botella: 30.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 52,
    seccion: ['Rioja'],
    vino: 'Marques De Riscal',
    envejecimiento: 'Reserva',
    anada: 2016,
    uvas: ['tempranillo', 'graciano'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 26.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 52,
    seccion: ['Rioja'],
    vino: 'Muga',
    envejecimiento: 'Crianza',
    anada: 2018,
    uvas: ['tempranillo', 'garnacha', 'mazuelo', 'graciano'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 27.0,
    top: false,
    new: false,
    last: false,
  },
  // {
  //   id: 52,
  //   seccion: ['Rioja'],
  //   vino: 'Viña Ardanza',
  //   envejecimiento: 'Reserva',
  //   anada: 2015,
  //   uvas: ['tempranillo', 'garnacha'],
  //   denominacion_origen: 'Rioja',
  //   precio_copa: 0,
  //   precio_botella: 32.0,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  {
    id: 52,
    seccion: ['Ribera Del Duero'],
    vino: 'Pago De Capellanes',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 0,
    precio_botella: 29.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 52,
    seccion: ['Ribera Del Duero'],
    vino: 'Protos',
    envejecimiento: 'Crianza',
    anada: 2017,
    uvas: ['tempranillo'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 0,
    precio_botella: 26.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 52,
    seccion: ['Otras DO'],
    vino: 'Entrechuelos',
    envejecimiento: 'Roble',
    anada: 2021,
    uvas: ['syrah', 'merlot', 'cabernet sauvignon', 'tintilla de rota'],
    denominacion_origen: 'Cadiz',
    precio_copa: 0,
    precio_botella: 16.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 52,
    seccion: ['Rioja'],
    vino: 'Azpilicueta',
    envejecimiento: 'Crianza',
    anada: 2018,
    uvas: ['tempranillo'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 18.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 54,
    seccion: ['Rioja'],
    vino: 'Lindes De Remelluri',
    envejecimiento: 'Cosecha',
    anada: 2018,
    uvas: ['tempranillo', 'garnacha'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 24.0,
    top: false,
    new: false,
    last: false,
  },
  // {
  //   id: 55,
  //   seccion: ['Otras DO'],
  //   vino: 'Entrechuelos Tercer Año',
  //   envejecimiento: 'Cosecha',
  //   anada: 2018,
  //   uvas: ['syrah', 'merlot', 'cabernet sauvignon', 'tintilla de rota'],
  //   denominacion_origen: 'Cadiz',
  //   precio_copa: 0,
  //   precio_botella: 34.0,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  // {
  //   id: 56,
  //   seccion: ['Otras DO'],
  //   vino: 'Garum',
  //   envejecimiento: 'Cosecha',
  //   anada: 2019,
  //   uvas: ['petit verdot', 'merlot', 'syrah', 'tintilla de rota'],
  //   denominacion_origen: 'Cadiz',
  //   precio_copa: 0,
  //   precio_botella: 19.9,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  {
    id: 56,
    seccion: ['Champagne Y Cava'],
    vino: 'Juve & Camps',
    envejecimiento: 'Reserva',
    anada: 2017,
    uvas: ['Brut'],
    denominacion_origen: 'Cataluña',
    precio_copa: 0,
    precio_botella: 24.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 56,
    seccion: ['Champagne Y Cava'],
    vino: 'MOET & CHANDON ICE IMPERIAL',
    envejecimiento: 'Reserva',
    anada: 2022,
    uvas: ['Brut'],
    denominacion_origen: 'Francia',
    precio_copa: 0,
    precio_botella: 85.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 56,
    seccion: ['Champagne Y Cava'],
    vino: 'Veuve Clicquot',
    envejecimiento: 'Reserva',
    anada: 2020,
    uvas: ['Brut'],
    denominacion_origen: 'Francia',
    precio_copa: 0,
    precio_botella: 58.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 56,
    seccion: ['Blancos Y Rosados'],
    vino: '828 - Rosado',
    envejecimiento: 'Cosecha',
    anada: 2021,
    uvas: ['garnacha'],
    denominacion_origen: 'Rioja',
    precio_copa: 3.0,
    precio_botella: 19.0,
    top: false,
    new: false,
    last: false,
  },

  {
    id: 57,
    seccion: ['Rioja'],
    vino: 'Amador Medrano',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 18.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 58,
    seccion: ['Rioja'],
    vino: 'Choza',
    envejecimiento: 'Crianza',
    anada: 2019,
    uvas: ['tempranillo'],
    denominacion_origen: 'Rioja',
    precio_copa: 2.9,
    precio_botella: 15.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 59,
    seccion: ['Rioja'],
    vino: 'Amador Medrano - Las Aguzaderas - Selección Especial',
    envejecimiento: 'Cosecha',
    anada: 2018,
    uvas: ['tempranillo'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 29.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 60,
    seccion: ['Rioja'],
    vino: 'Amador Medrano - Terra',
    envejecimiento: 'Cosecha',
    anada: 2018,
    uvas: ['tempranillo'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 21.0,
    top: false,
    new: true,
    last: false,
  },
  {
    id: 61,
    seccion: ['Rioja'],
    vino: 'Real Agrado - Canterabuey',
    envejecimiento: 'Cosecha',
    anada: 2018,
    uvas: ['garnacha'],
    denominacion_origen: 'Rioja',
    precio_copa: 0,
    precio_botella: 24.0,
    top: false,
    new: false,
    last: false,
  },
  {
    id: 61,
    seccion: ['Ribera Del Duero'],
    vino: 'Naxus',
    envejecimiento: 'Crianza',
    anada: 2018,
    uvas: ['tempranillo'],
    denominacion_origen: 'Ribera Del Duero',
    precio_copa: 0,
    precio_botella: 17.0,
    top: false,
    new: false,
    last: false,
  },
  // {
  //   id: 61,
  //   seccion: ['Otras DO'],
  //   vino: 'Habla Del Silencio',
  //   envejecimiento: 'Cosecha',
  //   anada: 2020,
  //   uvas: ['syrah', 'cabernet sauvignon', 'tempranillo'],
  //   denominacion_origen: 'Extremadura',
  //   precio_copa: 0,
  //   precio_botella: 21.9,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
  // {
  //   id: 61,
  //   seccion: ['Ribera Del Duero'],
  //   vino: 'Pago De Carraovejas',
  //   envejecimiento: 'Cosecha',
  //   anada: 2019,
  //   uvas: ['merlot', 'cabernet sauvignon', 'tempranillo'],
  //   denominacion_origen: 'Ribera Del Duero',
  //   precio_copa: 0,
  //   precio_botella: 42.0,
  //   top: false,
  //   new: false,
  //   last: false,
  // },
];
